### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by nihano**

### CODE REVIEW

**Comment by nihano** [comment]
branch has been created

**Comment by bahatas** [comment]
There is a conflict on the code for merge req( PR )... Generally after you created a PR, this conflict solution is on the lead or reviwer. Based on the method you defined on the project. 

Can you close this Pull request.

And then recreate with these codes 

Step 2: Switch to the head branch of the pull request.
git checkout feature/US1-student-service

Step 3: Merge the base branch into the head branch.
git merge master

Step 4: Fix the conflicts and commit the result.

Step 5: Push the changes.

git push -u origin feature/US1-student-service

**Review by bahatas — COMMENTED** [review]
recreate after close please.

**Comment by bahatas** [comment]
Closed by Baha

**Comment by bahatas** [comment]
you need to reopen again

**Pull request closed without merging**
